
// 禁止兼职
IF
	Kit(Player%slot%,c4Q06Fighter)
	OR(6)
		Class(Player%slot%,FIGHTER_MAGE)
		Class(Player%slot%,FIGHTER_CLERIC)
		Class(Player%slot%,FIGHTER_THIEF)
		Class(Player%slot%,FIGHTER_MAGE_THIEF)
		Class(Player%slot%,FIGHTER_DRUID)
		Class(Player%slot%,FIGHTER_MAGE_CLERIC)
THEN
	RESPONSE #100
		ActionOverride(Player%slot%,AddKit(TRUECLASS))
		Wait(1)
		DisplayStringHead(Player%slot%,@5)
		ActionOverride(Player%slot%,PauseGame())
		Continue()
END
	